modLoader="javafml"
license="license.txt"
loaderVersion="[33,)"
[[mods]]
modId="terraforged"
displayName="TerraForged"
version="${version}"
authors="dags"
credits="dags"
logoFile="terraforged.png"
displayURL="https://terraforged.com"
issueTrackerURL="https://github.com/TerraForged/TerraForged/issues"
description='''
Description:
 A terrain generator attempting to create more immersive, inspiring worlds to explore and build in!
'''